trigger:
- '*'

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  wwwrootDir: 'Tailspin.SpaceGame.Web/wwwroot'
  dotnetSdkVersion: '8.x'

steps:
# ✅ Use Node 18 LTS
- task: UseNode@1
  displayName: 'Use Node.js 18 LTS'
  inputs:
    version: '18.x'

# ✅ Install dependencies safely
- script: |
    npm cache clean --force
    npm install --legacy-peer-deps
  displayName: 'Install npm dependencies'

# ✅ Compile Sass assets
- script: |
    ./node_modules/.bin/node-sass $(wwwrootDir) --output $(wwwrootDir)
  displayName: 'Compile Sass assets'

# ✅ Run Gulp tasks
- task: Gulp@1
  displayName: 'Run Gulp tasks'

# ✅ Record build info
- script: 'echo "$(Build.DefinitionName), $(Build.BuildId), $(Build.BuildNumber)" > buildinfo.txt'
  displayName: 'Write build info'
  workingDirectory: $(wwwrootDir)

# ✅ .NET SDK setup
- task: UseDotNet@2
  displayName: 'Use .NET SDK $(dotnetSdkVersion)'
  inputs:
    packageType: sdk
    version: '$(dotnetSdkVersion)'

# ✅ Restore .NET project dependencies
- task: DotNetCoreCLI@2
  displayName: 'Restore project dependencies'
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# ✅ Build the .NET project
- task: DotNetCoreCLI@2
  displayName: 'Build the project - $(buildConfiguration)'
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration $(buildConfiguration)'
    projects: '**/*.csproj'

- template: templates/build.yml
  parameters:
    buildConfiguration: 'Debug'

- template: templates/build.yml
  parameters:
    buildConfiguration: 'Release'
    
# ✅ Publish the .NET project
- task: DotNetCoreCLI@2
  displayName: 'Publish the project - $(buildConfiguration)'
  inputs:
    command: 'publish'
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: '--no-build --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/$(buildConfiguration)'
    zipAfterPublish: true

# ✅ Publish artifacts
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact: drop'
  condition: succeeded()
